# Generated by Django 5.2.12 on 2026-03-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '__first__'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='contacts.supplier'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='supplier_name',
            field=models.CharField(help_text='Legacy name field', max_length=255),
        ),
    ]
