# Generated by Django 5.2.12 on 2026-03-14 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Always positive', max_digits=12)),
                ('move_type', models.CharField(choices=[('receipt', 'Receipt'), ('delivery', 'Delivery'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out')], max_length=20)),
                ('reference_type', models.CharField(help_text='e.g. Receipt, Delivery, Transfer, Adjustment', max_length=50)),
                ('reference_id', models.PositiveIntegerField(help_text='Links to source document PK')),
                ('reference_ref', models.CharField(help_text='e.g. RCP-2026-0042', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_out', to='warehouses.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='products.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_in', to='warehouses.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='warehouses.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='products.product')),
            ],
            options={
                'ordering': ['product', 'location'],
                'unique_together': {('product', 'location')},
            },
        ),
    ]
